name : vercel-deploy

on:
  push:
    branches:
      - main

  test:
    name: Testing of the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: Run tests 
        run: npm run test